// Generated by spider on 2023-03-11 01:35:01.229235

part of 'resources.dart';

class Images {
  Images._();

  static const String bagimage = 'assets/images/bagimage.png';
  static const String bgimage = 'assets/images/bgimage.png';
  static const String circleimage = 'assets/images/circleimage.png';
  static const String footerimage = 'assets/images/footerimage.png';
  static const String image24 = 'assets/images/image 24.png';
  static const String image25 = 'assets/images/image 25.png';
  static const String justImage = 'assets/images/just_image.png';
  static const String map = 'assets/images/map.png';
  static const String splash = 'assets/images/splash.png';
  static const String usWork = 'assets/images/us_work.png';
  static const String gropu = 'assets/images/Group.png';
}
