// Generated by spider on 2023-02-22 00:33:04.980680

part of 'resources.dart';

class Images {
  Images._();

  static const String gis = 'assets/images/2gis.png';
  static const String circleimage = 'assets/images/circleimage.png';
  static const String fifth = 'assets/images/fifth.png';
  static const String first = 'assets/images/first.png';
  static const String fourth = 'assets/images/fourth.png';
  static const String image24 = 'assets/images/image 24.png';
  static const String image25 = 'assets/images/image 25.png';
  static const String justImage = 'assets/images/just_image.png';
  static const String second = 'assets/images/second.png';
  static const String third = 'assets/images/third.png';
  static const String usWork = 'assets/images/us_work.png';
}
