// Generated by spider on 2023-02-14 22:47:15.216681

part of 'resources.dart';

class Images {
  Images._();

  static const String fifth = 'assets/images/fifth.png';
  static const String first = 'assets/images/first.png';
  static const String fourth = 'assets/images/fourth.png';
  static const String second = 'assets/images/second.png';
  static const String third = 'assets/images/third.png';
}
