// Generated by spider on 2023-03-11 01:35:01.380804

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String afterGuurantee = 'assets/svgs/after_guurantee.svg';
  static const String afterRemont = 'assets/svgs/after_remont.svg';
  static const String building = 'assets/svgs/building.svg';
  static const String consulting = 'assets/svgs/consulting.svg';
  static const String cvalification = 'assets/svgs/cvalification.svg';
  static const String instagram = 'assets/svgs/instagram.svg';
  static const String menu = 'assets/svgs/menu.svg';
  static const String menuBlack = 'assets/svgs/menu_black.svg';
  static const String mnogoOpyt = 'assets/svgs/mnogo_opyt.svg';
  static const String montaj = 'assets/svgs/montaj.svg';
  static const String phone = 'assets/svgs/phone.svg';
  static const String selimBlacck = 'assets/svgs/selim_blacck.svg';
  static const String selimBluee = 'assets/svgs/selim_bluee.svg';
  static const String selimG = 'assets/svgs/selim_g.svg';
  static const String settingsRemote = 'assets/svgs/settings_remote.svg';
  static const String success = 'assets/svgs/success.svg';
  static const String time = 'assets/svgs/time.svg';
  static const String whatsapp = 'assets/svgs/whatsapp.svg';
  static const String zakazatVorota = 'assets/svgs/zakazat_vorota.svg';
}
