// Generated by spider on 2023-02-13 22:18:49.005415

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String afterGuurantee = 'assets/svgs/after_guurantee.svg';
  static const String afterRemont = 'assets/svgs/after_remont.svg';
  static const String building = 'assets/svgs/building.svg';
  static const String cvalification = 'assets/svgs/cvalification.svg';
  static const String instagram = 'assets/svgs/instagram.svg';
  static const String menuBlack = 'assets/svgs/menu_black.svg';
  static const String mnogoOpyt = 'assets/svgs/mnogo_opyt.svg';
  static const String montaj = 'assets/svgs/montaj.svg';
  static const String selimBlack = 'assets/svgs/selim_black.svg';
  static const String time = 'assets/svgs/time.svg';
  static const String whatsapp = 'assets/svgs/whatsapp.svg';
}
